markdown:       kramdown
kramdown:
        input: GFM
        extensions:
                - autolink
                - footnotes
                - smart
        enable_coderay: true
        syntax_highlighter: rouge
        syntax_highlighter_opts:
                ine_numbers:  nil
permalink: /:year/:month/:title/
url: http://yanshuo.name/cn
homepage: http://yanshuo.name
author: 石见石页_
highlighter: rouge

