markdown:       kramdown
kramdown:
        input: GFM
        remove_line_breaks_for_cjk: true
        extensions:
                - autolink
                - footnotes
                - smart
        enable_coderay: true
        syntax_highlighter: rouge
        syntax_highlighter_opts:
                line_numbers: false

permalink: /:year/:month/:title/
url: https://yanshuo.site/cn
homepage: https://yanshuo.site
author: 石见石页
highlighter: rouge
# port: 4000
# host: 127.0.0.1
plugins:
  - jekyll-feed
