markdown:       kramdown
kramdown:
        input: GFM
        extensions:
                - autolink
                - footnotes
                - smart
        enable_coderay: true
        syntax_highlighter: rouge
        syntax_highlighter_opts:
                ine_numbers:  nil
permalink: /:year/:month/:title/
url: https://dustincys.github.io/cn
homepage: https://dustincys.github.io
author: 石见石页
highlighter: rouge
