markdown:       kramdown
kramdown:
        input: GFM
        remove_line_breaks_for_cjk: true
        extensions:
                - autolink
                - footnotes
                - smart
        enable_coderay: true
        syntax_highlighter: rouge
        syntax_highlighter_opts:
                line_numbers:  nil

permalink: /:year/:month/:title/
url: https://yanshuo.name/cn
homepage: https://yanshuo.name
author: 石见石页
highlighter: rouge
